
services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng

    ports:
      - "8080:8080"

    environment:
      SEARXNG_BASE_URL: http://localhost:8080/
      SEARXNG_LIMITER: "false"

    volumes:
      - ./searxng:/etc/searxng

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 15s
      timeout: 5s
      retries: 10

  mcp-searxng:
    image: overtlids/mcp-searxng-enhanced:latest
    container_name: mcp-searxng

    depends_on:
      searxng:
        condition: service_healthy

    ports:
      - "9090:9090"

    environment:
      MCP_HTTP_HOST: 0.0.0.0
      MCP_HTTP_PORT: 9090

      # Internal Docker address
      SEARXNG_ENGINE_API_BASE_URL: http://searxng:8080/search

      DESIRED_TIMEZONE: Asia/Tehran

      RETURNED_SCRAPPED_PAGES_NO: 3
      SCRAPPED_PAGES_NO: 5
      PAGE_CONTENT_WORDS_LIMIT: 5000
      CITATION_LINKS: "True"

      MAX_IMAGE_RESULTS: 10
      MAX_VIDEO_RESULTS: 10
      MAX_FILE_RESULTS: 5
      MAX_MAP_RESULTS: 5
      MAX_SOCIAL_RESULTS: 5

      TRAFILATURA_TIMEOUT: 15
      SCRAPING_TIMEOUT: 20

    restart: unless-stopped